window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/0q.jpg' class='c_head_img_img' /></div>"+"摇优惠券买爆款酒 全在老白干微店！");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/1q.jpg' class='c_head_img_img' /></div>"+"中秋佳节送啥礼，当然是十八酒坊啦！");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/2q.jpg' class='c_head_img_img' /></div>"+"大家有摇一摇摇到什么奖品吗");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/3q.jpg' class='c_head_img_img' /></div>"+"有意思 摇到优惠券试了下 买酒好方便。");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/4q.jpg' class='c_head_img_img' /></div>"+"亲，摇奖到手软 不如进店逛逛吧");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/5q.jpg' class='c_head_img_img' /></div>"+"帅帅帅，你最帅！");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/6q.jpg' class='c_head_img_img' /></div>"+"好看好看，还有奖拿！");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/7q.jpg' class='c_head_img_img' /></div>"+"好看好看好看~");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/8q.jpg' class='c_head_img_img' /></div>"+"中奖，中奖，求中奖");
window.CACHEMSG.push("<div class='c_head_img'><img src='./images/head/9q.jpg' class='c_head_img_img' /></div>"+"哈哈摇到20元 立马买了瓶 便宜！");