window.CACHEMSG.push("看完央视又来看河北，真的是很好看啊");
window.CACHEMSG.push("大花花萌萌哒");
window.CACHEMSG.push("东北大妞加东北大饼");
window.CACHEMSG.push("叶夫根尼太萌");
window.CACHEMSG.push("问世间情为何物 只为王大花生死相许");
window.CACHEMSG.push("世间特工千千万 唯有大花最彪悍");
window.CACHEMSG.push("继续看这部良心之作");
window.CACHEMSG.push("看预告片就好期待了");
window.CACHEMSG.push("据说我只要说句话，就会有人赞我！！");
window.CACHEMSG.push("做人好累啊，下辈子要变成鱼锅饼子");